### ISSUE TITLE
Auto Complete not working for me.

### ISSUE THREAD

**Issue by dimpu** [victorvoid/vim-frontend#6]
First of all thank you so much for this git.
This is exactly what I'm looking for.

I'm not able to see auto-complete as you showing in your videos. I have done everything as per the README file. 

I'm using MAC book Air.
Also getting these errors
line    8:
E117: Unknown function: dein#begin
line   13:
E117: Unknown function: dein#add
line   14:
E117: Unknown function: dein#add
line   17:
E117: Unknown function: dein#add
line   20:
E117: Unknown function: dein#add
line   23:
E117: Unknown function: dein#add
line   26:
E117: Unknown function: dein#add
line   27:
E117: Unknown function: dein#add
line   30:
E117: Unknown function: dein#add
line   33:
E117: Unknown function: dein#add
line   36:
E117: Unknown function: dein#add
line   39:
E117: Unknown function: dein#add
line   42:
E117: Unknown function: dein#add
line   45:
E117: Unknown function: dein#add
line   48:
E117: Unknown function: dein#add
line   51:
E117: Unknown function: dein#add
line   54:
E117: Unknown function: dein#add
line   57:
E117: Unknown function: dein#add
line   60:
E117: Unknown function: dein#add
line   63:
E117: Unknown function: dein#add
line   64:
E117: Unknown function: dein#add
line   67:
E117: Unknown function: dein#add
line   70:
E117: Unknown function: dein#add
line   71:
E117: Unknown function: dein#add
line   74:
E117: Unknown function: dein#add
line   75:
E117: Unknown function: dein#add
line   76:
E117: Unknown function: dein#add
line   77:
E117: Unknown function: dein#add
line   80:
E117: Unknown function: dein#add
line   81:
E117: Unknown function: dein#add
line   82:
E117: Unknown function: dein#add
line   83:
E117: Unknown function: dein#add
line   84:
E117: Unknown function: dein#add
line   87:
E117: Unknown function: dein#add
line   88:
E117: Unknown function: dein#add
line   89:
E117: Unknown function: dein#add
line   90:
E117: Unknown function: dein#add
line   93:
E117: Unknown function: dein#add
line   94:
E117: Unknown function: dein#add
line   95:
E117: Unknown function: dein#add
line   98:
E117: Unknown function: dein#end
line  100:
E117: Unknown function: dein#check_install
E15: Invalid expression: dein#check_install()
line  162:
E185: Cannot find color scheme 'Benokai'
Press ENTER or type command to continue

**Comment by victorvoid** [comment]
It looks like it was not installed dein plugin manager, try running it:

`$ curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > installer.sh
`

`$ sh ./installer.sh` {specify the installation directory}

**Comment by IsmaelEzequiel** [comment]
@victorvoid Really thanks XD
