### ISSUE TITLE
YouCompleteMe not installed

### ISSUE THREAD

**Issue by IsmaelEzequiel** [victorvoid/vim-frontend#7]
Please, help me. :/

Messages maintainer: Bram Moolenaar <Bram@vim.org>
[dein] Not installed plugins: ['vim-surround', 'vim-session', 'tern_for_vim', 'vim-javascript-syntax', 'vim-css3-syntax', 'vim-airline', 'vim-airline-
themes', 'ctrlp.vim', 'vim-gitgutter', 'vim-nerdtree-tabs', 'vim-multiple-cursors', 'vim-colorschemes', 'syntastic', 'emmet-vim', 'sourcebeautify.vim'
, 'HTML-AutoCloseTag', 'vim-fugitive', 'ultisnips', 'vim-trailing-whitespace', 'auto-pairs', 'nerdtree', 'vimshell.vim', 'vim-jade', 'vim-commentary',
 'vim-jsx', 'vim-haml', 'CSApprox', 'indentLine', 'vim-less', 'vim-snippets', 'vim-stylus', 'vimproc.vim', 'tagbar', 'YouCompleteMe', 'typescript-vim'
, 'vim-angular', 'vim-coloresque', 'vim-misc', 'vim-polyglot']
[dein] Update started: (2017/06/26 18:43:55)
[dein] /home/ismael/.cache/dein/repos/github.com/Valloric/YouCompleteMe
[dein] Maybe wrong username or repository.
[dein] Process timeout: (2017/06/26 18:49:28)
[dein] Updated plugins:
[dein]   tern_for_vim(1 change)
[dein]   vim-javascript-syntax(1 change)
[dein]   vim-css3-syntax(1 change)
[dein]   vim-airline(1 change)
[dein]   vim-airline-themes(1 change)
[dein]   ctrlp.vim(1 change)
[dein]   vim-surround(1 change)
[dein]   vim-session(1 change)
[dein]   vim-nerdtree-tabs(1 change)                                                                                                                  
[dein]   vim-colorschemes(1 change)                                                                                                                   
[dein]   emmet-vim(1 change)                                                                                                                          
[dein]   sourcebeautify.vim(1 change)                                                                                                                 
[dein]   HTML-AutoCloseTag(1 change)                                                                                                                  
[dein]   vim-gitgutter(1 change)                                                                                                                      
[dein]   vim-multiple-cursors(1 change)                                                                                                               
[dein]   syntastic(1 change)                                                                                                                          
[dein]   vim-trailing-whitespace(1 change)                                                                                                            
[dein]   auto-pairs(1 change)                                                                                                                         
[dein]   nerdtree(1 change)                                                                                                                           
[dein]   vim-fugitive(1 change)                                                                                                                       
[dein]   vim-jade(1 change)                                                                                                                           
[dein]   vim-commentary(1 change)                                                                                                                     
[dein]   vim-jsx(1 change)     
[dein]   vim-haml(1 change)                                                                                                                           
[dein]   CSApprox(1 change)                                                                                                                           
[dein]   ultisnips(1 change)                                                                                                                          
[dein]   vimshell.vim(1 change)                                                                                                                       
[dein]   vim-less(1 change)                                                                                                                           
[dein]   vim-snippets(1 change)                                                                                                                       
[dein]   vim-stylus(1 change)                                                                                                                         
[dein]   vimproc.vim(1 change)                                                                                                                        
[dein]   tagbar(1 change)                                                                                                                             
[dein]   indentLine(1 change)                                                                                                                         
[dein]   typescript-vim(1 change)                                                                                                                     
[dein]   vim-angular(1 change)                                                                                                                        
[dein]   vim-coloresque(1 change)                                                                                                                     
[dein]   vim-misc(1 change)                                                                                                                           
[dein]   vim-polyglot(1 change)                                                                                                                       
[dein] Error installing plugins:                                                                                                                      
[dein]   YouCompleteMe                                                                                                                                
[dein] Please read the error message log with the :message command.                                                                                   
[dein] Done: (2017/06/26 18:50:04)

**Comment by victorvoid** [comment]
Try it: 
` curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > installer.sh `

**Comment by victorvoid** [comment]
fixed [here](https://github.com/victorvoid/vim-frontend/issues/6)
