### ISSUE TITLE
Cannot find color scheme ‘Tomorrow-Dark’

### ISSUE THREAD

**Issue by aniude** [victorvoid/vim-frontend#9]
Hi, when I have finished the enviroment install, I found that the color sheme error. How can I find this scheme, for example, only I found is like Tomorrow-Night.

**Comment by victorvoid** [comment]
Can you show me a screenshot ?

**Comment by aniude** [comment]
![screen shot 2018-07-13 at 13 06 10](https://user-images.githubusercontent.com/1137266/42673376-ad593c72-869d-11e8-8370-d4c5fe15a3f7.png)

**Comment by victorvoid** [comment]
Thanks @aniude! fixed in [21ceeadc](https://github.com/victorvoid/vim-frontend/commit/21ceeadc62b921412786b61023fe4281cc0e4df9) to use Tomorrow-Night.

**Comment by aniude** [comment]
👍 thank @victorvoid
